In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [4]:
myarr = np.array(mylist)
myarr

array([1, 2, 3])

In [5]:
type(myarr)

numpy.ndarray

In [7]:
my_matrix = [[1,2,3], [4,5,6], [7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(1,50, 10)

array([ 1, 11, 21, 31, 41])

In [ ]:
np.linspace(1, 10, num=4) # [start, endpoint, numbers includes]

array([ 1.,  4.,  7., 10.])

In [ ]:
np.eye(2) # identity matrix which diagonl includes 1

array([[1., 0.],
       [0., 1.]])

In [14]:
np.random.rand()

0.808414785773642

In [17]:
np.random.seed(19)
np.random.rand(2)

array([0.0975336 , 0.76124972])